name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pytest
  - pytest-asyncio !=0.22.0
  - pytest-benchmark
  - pytest-cov
  - pytest-mock
  - pytest-vcr
  - pip
  - pytest<8
  - ujson
  - requests
  - decorator
  - pytest-timeout
  - google-auth
  - aiohttp
  - google-auth-oauthlib
  - flake8
  - black
  - google-cloud-core
  - google-api-core
  - google-api-python-client
  - httpretty
  - aiobotocore
  - "moto >=4,<5"
  - flask
