name: test_env
channels:
  - conda-forge
dependencies:
  - aiohttp
  - pip
  - requests
  - zstandard
  - python-snappy
  - lz4<3.1.3
  - pyftpdlib
  - cloudpickle
  - pytest
  - pytest-asyncio
  - pytest-benchmark
  - pytest-cov
  - pytest-mock
  - pytest-vcr
  - python-libarchive-c
  - py
  - numpy
  - nomkl
  - tqdm
