name: fsspec
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - paramiko
  - requests
  - numpydoc
  - aiohttp
  - pygit2
  - distributed
  - pyarrow=1
  - libarchive
  - smbprotocol
